version: 2
updates:
  # Python dependencies (pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "python-team"
    assignees:
      - "security-team"
    labels:
      - "dependencies"
      - "python"
      - "security"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Group related updates
    groups:
      production-dependencies:
        patterns:
          - "django*"
          - "flask*"
          - "fastapi*"
          - "sqlalchemy*"
      development-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "flake8"
          - "mypy"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
      - "infrastructure"
    commit-message:
      prefix: "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"

  # Poetry (if using Poetry)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "poetry"
    # Custom configuration for Poetry
    versioning-strategy: "lockfile-only"
